name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch, may also be named 'master' or 'develop'
jobs:
  build:
    name: build, pack & 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          persist-credentials: false
      - name: restore
        run: dotnet restore WeakMemoryCache/WeakMemoryCache.csproj
      - name: build
        run: |
          dotnet build WeakMemoryCache/WeakMemoryCache.csproj \
            --configuration Release \
            --no-restore \
            -p:ContinuousIntegrationBuild=true -v:m
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nugets
          path: ./WeakMemoryCache/bin/Release/
  publish:
    name: nuget push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: build
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: nugets
      - run: ls

          
